### ISSUE TITLE
I cannot install the script

### ISSUE THREAD

**Issue by osmansalih** [ruscoe/tincan#11]
install.php:
![install php](https://github.com/user-attachments/assets/c5358d8d-2c7e-4b87-a41a-963546db2ce9)
index.php:
![index php](https://github.com/user-attachments/assets/f322c87b-6d08-4092-9bf7-eb40d7991299)

I did all of requirements in readme.md

**Comment by ruscoe** [comment]
Sorry you're having trouble!

I'm not familiar with xampp, but it looks like you're missing the environment variables. You can find them [here in the Docker configuration](https://github.com/ruscoe/tincan/blob/main/docker-compose.yml#L25-L33).

**Comment by osmansalih** [comment]
nvm I did it 

`docker compose up`
but this command took a lot of time but when it finished I went to localhost and I found the installation page

**Comment by osmansalih** [comment]
Thanks
