### ISSUE TITLE
I liked your project

### ISSUE THREAD

**Issue by osmansalih** [ruscoe/tincan#12]
I would help you with your project but the project structure seems a bit complicated as there are many folders that I have not dealt with before such as the vendor and core folders

 Also why you are using the scss format instead of css? what's the difference between them

**Comment by ruscoe** [comment]
The scss files are Sass files. Sass is just a way of writing CSS more efficiently. Take a look here for information:

https://sass-lang.com/guide/#variables

**Comment by osmansalih** [comment]
Thanks
